### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by joehoeller** [wiamsuri/django-gunicorn-nginx-docker#1]
Not sure why  but the containers are up, but nothing is serving, error: 502 Bad Gateway
nginx/1.14.2

**Comment by wiamsuri** [comment]
Your nginx container is up, but the container with django has error and refuse to start. My guess is you might forgot to put environment variables in django.env. Can you check your `django.env` file and make sure that the variable `MYSITE_SECRET_KEY` has a value?

**Comment by joehoeller** [comment]
I did do that.

**Comment by joehoeller** [comment]
Is this meant to be ran on a laptop or an actual VM in the cloud?

**Comment by wiamsuri** [comment]
It's meant to be run on actual instance in the cloud. When you are developing your app, you can simply use “python manage.py runserver” for developments on your laptop.

**Comment by joehoeller** [comment]
I sent you screen shots to email.
