### ISSUE TITLE
How to configure it to work with AWS?

### ISSUE THREAD

**Issue by game-libgdx-unity** [wiamsuri/django-gunicorn-nginx-docker#10]
I managed to run the local server successfully with docker following by your instructions. It would be really helpful for everyone if you write more steps to deploy this on live env such as aws eks or google kubernetes engine.

**Comment by wiamsuri** [comment]
Hello,

The content of this repository is only limited to containerizing a Django website with Docker. Deploying the Docker container in Kubernetes environment is outside the scope of what I intended to have here in this repository. However, I can give some clues of how to do that.

1. You will need set up a Kubernetes cluster. https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html
2. Setup Nginx Ingress Controller with Helm. https://github.com/kubernetes/ingress-nginx/tree/master/charts/ingress-nginx
3. Create a Helm chart and customize it for the project. https://helm.sh/docs/helm/helm_create/
4. Deploy to Kubernetes cluster with Helm.

That is how I would deploy this to a cluster on EKS. If you have any more question, let me know,

**Comment by joehoeller** [comment]
Google search for Django helm:

https://www.google.com/amp/s/davidmburke.com/2020/01/24/deploy-django-with-helm-to-kubernetes/amp/

**Comment by wiamsuri** [comment]
Closing issue
