### ISSUE TITLE
Port 8080

### ISSUE THREAD

**Issue by Bastilla123** [wiamsuri/django-gunicorn-nginx-docker#4]
Hello,

my port 80 ist allready with another app linked. Now i change in docker.compose.yml ports: - "8080:8080" but when i make on host curl localhost:8080 then i get: curl: (56) Recv failure: Connection reset by peer

docker ps show me:
f416c908f272        nginx:1.17                         "nginx -g 'daemon of…"   17 minutes ago      Up 17 minutes       80/tcp, 0.0.0.0:8080->8080/tcp   ngx
8fa958d8cc3c        django-gunicorn-nginx-docker_app   "gunicorn --workers=…"   18 minutes ago      Up 18 minutes       0.0.0.0:8000->8000/tcp           django-gunicorn

**Comment by wiamsuri** [comment]
You will have to change the nginx config file to listen to port 8080 instead of port 80

**Comment by artsiom1104** [comment]
You don't change 80 port. because the 80 port is used inside of Nginx docker. not 80 port of localhost.
